version: '3.2'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: foreman start -f Procfile.dev -p 3000
    volumes: 
      - ./api:/project
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - '3001:3000'
      - '35729:35729'
    depends_on:
      - db